name: Publish Extension

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Sample/**'
      - README.md
      - '*.png'
      - '**/*.png'
      - '.github/CODEOWNERS'
      - 'CONTRIBUTING.md'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-acr:
    name: Deploy ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deployment Infra
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          name: CloudFlareExtensionACR
          location: uksouth
          template-file: ./Infra/main.bicep
          parameters-file: ./Infra/main.bicepparam

  publish-extension:
    needs: deploy-acr
    name: Publish CloudFlare Bicep extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Bicep
        run: |
          az config set bicep.use_binary_from_path=false
          az bicep install

      - name: Run nbgv
        id: nbgv
        uses: dotnet/nbgv@v0.4.2

      - name: Publish Extension
        shell: pwsh
        run: |
          $env:BICEP_TRACING_ENABLED = "true"
          [string] $target = "br:cloudflarebicep.azurecr.io/cloudflare:${{ steps.nbgv.outputs.SimpleVersion }}"
          ./Infra/Scripts/Publish-Extension.ps1 -Target $target
          Write-Host "Published extension \`${$target}\`." >> $GITHUB_STEP_SUMMARY